# Generated by Django 3.1.4 on 2021-10-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='id',
            new_name='advisor_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='id',
            new_name='booking_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
